const types = {
  INCREMENT_START: 'INCREMENT_START',
  INCREMENT_SUCCESS: 'INCREMENT_SUCCESS',
  INCREMENT_ERROR: 'INCREMENT_ERROR',

  DECREMENT_START: 'DECREMENT_START',
  DECREMENT_SUCCESS: 'DECREMENT_SUCCESS',
  DECREMENT_ERROR: 'DECREMENT_ERROR',

  ASYNC_START: 'ASYNC_START',
  ASYNC_SUCCESS: 'ASYNC_SUCCESS',
  ASYNC_ERROR: 'ASYNC_ERROR',
};

export default types;
